//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T5008SlipView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T5008SlipView.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION.
        /// </summary>
        public static string CRAImportActionText {
            get {
                return ResourceManager.GetString("CRAImportActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add As New.
        /// </summary>
        public static string CRAImportAddAsNewKey {
            get {
                return ResourceManager.GetString("CRAImportAddAsNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA Website has been launched in a seperate browser window.
        /// </summary>
        public static string CRAImportBrowserLaunchNotificationKey {
            get {
                return ResourceManager.GetString("CRAImportBrowserLaunchNotificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CRAImportCancelKey {
            get {
                return ResourceManager.GetString("CRAImportCancelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check/UnCheck All.
        /// </summary>
        public static string CRAImportCheckAllText {
            get {
                return ResourceManager.GetString("CRAImportCheckAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CRAImportCloseKey {
            get {
                return ResourceManager.GetString("CRAImportCloseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CRAImportCollapseAllKey {
            get {
                return ResourceManager.GetString("CRAImportCollapseAllKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string CRAImportCostText {
            get {
                return ResourceManager.GetString("CRAImportCostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Import Completed.
        /// </summary>
        public static string CRAImportDataImportCompletedTitleKey {
            get {
                return ResourceManager.GetString("CRAImportDataImportCompletedTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the updated status list.
        /// </summary>
        public static string CRAImportDataImportReviewStatus {
            get {
                return ResourceManager.GetString("CRAImportDataImportReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Import Worksheet.
        /// </summary>
        public static string CRAImportDataImportWorksheetText {
            get {
                return ResourceManager.GetString("CRAImportDataImportWorksheetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string CRAImportDetailsText {
            get {
                return ResourceManager.GetString("CRAImportDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA Data Import.
        /// </summary>
        public static string CRAImportDownloadingDataTitleKey {
            get {
                return ResourceManager.GetString("CRAImportDownloadingDataTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to import data into ProFile.
        /// </summary>
        public static string CRAImportDownloadingDescriptionKey {
            get {
                return ResourceManager.GetString("CRAImportDownloadingDescriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string CRAImportExpandAllKey {
            get {
                return ResourceManager.GetString("CRAImportExpandAllKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string CRAImportFailureKey {
            get {
                return ResourceManager.GetString("CRAImportFailureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed. Please cancel this session and try again..
        /// </summary>
        public static string CRAImportFailureMessage {
            get {
                return ResourceManager.GetString("CRAImportFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOVERNMENT DOWNLOADED DATA.
        /// </summary>
        public static string CRAImportGovernmentDownloadedDataText {
            get {
                return ResourceManager.GetString("CRAImportGovernmentDownloadedDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        public static string CRAImportGrossText {
            get {
                return ResourceManager.GetString("CRAImportGrossText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string CRAImportHistoryText {
            get {
                return ResourceManager.GetString("CRAImportHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Selected Data.
        /// </summary>
        public static string CRAImportImportSelectedDataTitleKey {
            get {
                return ResourceManager.GetString("CRAImportImportSelectedDataTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string CRAImportIssuerText {
            get {
                return ResourceManager.GetString("CRAImportIssuerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch CRA Website.
        /// </summary>
        public static string CRAImportLaunchCRAWebsiteMessage {
            get {
                return ResourceManager.GetString("CRAImportLaunchCRAWebsiteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINE ITEM.
        /// </summary>
        public static string CRAImportLineItemText {
            get {
                return ResourceManager.GetString("CRAImportLineItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in and enter details.
        /// </summary>
        public static string CRAImportLogInMessage {
            get {
                return ResourceManager.GetString("CRAImportLogInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to the site.
        /// </summary>
        public static string CRAImportManualLoginInstructionOneKey {
            get {
                return ResourceManager.GetString("CRAImportManualLoginInstructionOneKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your client&apos;s SINs to start importing data into ProFile.
        /// </summary>
        public static string CRAImportManualLoginInstructionTwoKey {
            get {
                return ResourceManager.GetString("CRAImportManualLoginInstructionTwoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        public static string CRAImportNoNameSelected {
            get {
                return ResourceManager.GetString("CRAImportNoNameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Some information may have been imported to ProFile (e.g. CDE info, Instalments, etc will be found in the Data Import Summary).
        /// </summary>
        public static string CRAImportNoSlipsForSelectedClientsMessageKey {
            get {
                return ResourceManager.GetString("CRAImportNoSlipsForSelectedClientsMessageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace {0}.
        /// </summary>
        public static string CRAImportReplaceInfoKey {
            get {
                return ResourceManager.GetString("CRAImportReplaceInfoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and Complete.
        /// </summary>
        public static string CRAImportReviewAndCompleteTitleKey {
            get {
                return ResourceManager.GetString("CRAImportReviewAndCompleteTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the imported data below.
        /// </summary>
        public static string CRAImportReviewDataText {
            get {
                return ResourceManager.GetString("CRAImportReviewDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Log In.
        /// </summary>
        public static string CRAImportSecureLogInTextKey {
            get {
                return ResourceManager.GetString("CRAImportSecureLogInTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Client List.
        /// </summary>
        public static string CRAImportSelectedClientsTitleKey {
            get {
                return ResourceManager.GetString("CRAImportSelectedClientsTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string CRAImportSuccessKey {
            get {
                return ResourceManager.GetString("CRAImportSuccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA Data Import.
        /// </summary>
        public static string CRAImportTitleKey {
            get {
                return ResourceManager.GetString("CRAImportTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang tight while we import your data into ProFile.
        /// </summary>
        public static string CRAImportWebsiteFailureMessage {
            get {
                return ResourceManager.GetString("CRAImportWebsiteFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CRAImportWelcomeCancel {
            get {
                return ResourceManager.GetString("CRAImportWelcomeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick. Easy. Secure.
        /// </summary>
        public static string CRAImportWelcomeDescription {
            get {
                return ResourceManager.GetString("CRAImportWelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save time by automatically importing client information.
        /// </summary>
        public static string CRAImportWelcomeHelpOne {
            get {
                return ResourceManager.GetString("CRAImportWelcomeHelpOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure client data is always accurate and up-to-date.
        /// </summary>
        public static string CRAImportWelcomeHelpThree {
            get {
                return ResourceManager.GetString("CRAImportWelcomeHelpThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent manual data entry errors.
        /// </summary>
        public static string CRAImportWelcomeHelpTwo {
            get {
                return ResourceManager.GetString("CRAImportWelcomeHelpTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch CRA Import Website.
        /// </summary>
        public static string CRAImportWelcomeLaunch {
            get {
                return ResourceManager.GetString("CRAImportWelcomeLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile CRA Data Import.
        /// </summary>
        public static string CRAImportWelcomeMessage {
            get {
                return ResourceManager.GetString("CRAImportWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carried Forward.
        /// </summary>
        public static string FileStatus_CarriedForward {
            get {
                return ResourceManager.GetString("FileStatus_CarriedForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string FileStatus_Completed {
            get {
                return ResourceManager.GetString("FileStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Partner Review.
        /// </summary>
        public static string FileStatus_InPartnerReview {
            get {
                return ResourceManager.GetString("FileStatus_InPartnerReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Preparer Review.
        /// </summary>
        public static string FileStatus_InPreparerReview {
            get {
                return ResourceManager.GetString("FileStatus_InPreparerReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Filing.
        /// </summary>
        public static string FileStatus_NotFiling {
            get {
                return ResourceManager.GetString("FileStatus_NotFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        public static string FileStatus_Printed {
            get {
                return ResourceManager.GetString("FileStatus_Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready To Print.
        /// </summary>
        public static string FileStatus_ReadyToPrint {
            get {
                return ResourceManager.GetString("FileStatus_ReadyToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string FileStatus_Unknown {
            get {
                return ResourceManager.GetString("FileStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Client.
        /// </summary>
        public static string FileStatus_WaitingForClient {
            get {
                return ResourceManager.GetString("FileStatus_WaitingForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work In Progress.
        /// </summary>
        public static string FileStatus_WorkInProgress {
            get {
                return ResourceManager.GetString("FileStatus_WorkInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Hub_ActionBar_AllString {
            get {
                return ResourceManager.GetString("Hub_ActionBar_AllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        public static string HUB_Add_Note_Key {
            get {
                return ResourceManager.GetString("HUB_Add_Note_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Hub_AvailableString {
            get {
                return ResourceManager.GetString("Hub_AvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters remaining.
        /// </summary>
        public static string HUB_CharacterLengthLimitMessage {
            get {
                return ResourceManager.GetString("HUB_CharacterLengthLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we update the status of the file for you.
        /// </summary>
        public static string Hub_ClientFileStatusUpdateProgressMessage {
            get {
                return ResourceManager.GetString("Hub_ClientFileStatusUpdateProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Hub_EmailTitleKey {
            get {
                return ResourceManager.GetString("Hub_EmailTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ProFile Hub.
        /// </summary>
        public static string Hub_Enable_TextKey {
            get {
                return ResourceManager.GetString("Hub_Enable_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Hub has encountered errors while trying to index some of the files. Please ensure that the files are not currently in use and try again later..
        /// </summary>
        public static string Hub_FailToIndexMessage_Key {
            get {
                return ResourceManager.GetString("Hub_FailToIndexMessage_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location for files is currently unavailable. If they are located on a network drive please check network connection. If you wish to change the location of files click Go to Setup..
        /// </summary>
        public static string Hub_FolderNotAvailable {
            get {
                return ResourceManager.GetString("Hub_FolderNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location for the Files is Unavailable.
        /// </summary>
        public static string Hub_FolderNotAvailableHeader {
            get {
                return ResourceManager.GetString("Hub_FolderNotAvailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing Files....
        /// </summary>
        public static string Hub_IndexingFilesString {
            get {
                return ResourceManager.GetString("Hub_IndexingFilesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Login in order to use Intuit Link.
        /// </summary>
        public static string HUB_LinkSignInMessage {
            get {
                return ResourceManager.GetString("HUB_LinkSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item Selected.
        /// </summary>
        public static string HUB_NoItemSelectedKey {
            get {
                return ResourceManager.GetString("HUB_NoItemSelectedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Hub is coming soon! It’s currently in Beta. If you would like to participate in the Beta please email: Graham_Sharples@intuit.com.
        /// </summary>
        public static string Hub_NotAvailableMessage {
            get {
                return ResourceManager.GetString("Hub_NotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait we add the note to the file.
        /// </summary>
        public static string HUB_Note_Adding_MessageKey {
            get {
                return ResourceManager.GetString("HUB_Note_Adding_MessageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Hub_NoteEditor_Cancel {
            get {
                return ResourceManager.GetString("Hub_NoteEditor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note:.
        /// </summary>
        public static string Hub_NoteEditor_Label {
            get {
                return ResourceManager.GetString("Hub_NoteEditor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Hub_NoteEditor_Ok {
            get {
                return ResourceManager.GetString("Hub_NoteEditor_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        public static string Hub_NoteEditor_Title {
            get {
                return ResourceManager.GetString("Hub_NoteEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Hub.
        /// </summary>
        public static string Hub_ProFileHubHeader {
            get {
                return ResourceManager.GetString("Hub_ProFileHubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Client Name or File Name).
        /// </summary>
        public static string Hub_SearchLabelKey {
            get {
                return ResourceManager.GetString("Hub_SearchLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Client(s):  {0} | Selected Client(s):  {1}.
        /// </summary>
        public static string Hub_SelectionStatusMessage {
            get {
                return ResourceManager.GetString("Hub_SelectionStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Hub Service: {0}.
        /// </summary>
        public static string Hub_ServiceStatusMessage {
            get {
                return ResourceManager.GetString("Hub_ServiceStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the lock to make changes..
        /// </summary>
        public static string Hub_SettingsLocked_Key {
            get {
                return ResourceManager.GetString("Hub_SettingsLocked_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Password.
        /// </summary>
        public static string Hub_SettingsPasswordHeader_Key {
            get {
                return ResourceManager.GetString("Hub_SettingsPasswordHeader_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Hub_SettingsPasswordLabel_Key {
            get {
                return ResourceManager.GetString("Hub_SettingsPasswordLabel_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the lock to prevent further changes..
        /// </summary>
        public static string Hub_SettingsUnlocked_Key {
            get {
                return ResourceManager.GetString("Hub_SettingsUnlocked_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is currently under BETA and is purely for Preview purposes..
        /// </summary>
        public static string Hub_Setup_BetaNoticeMessage_Key {
            get {
                return ResourceManager.GetString("Hub_Setup_BetaNoticeMessage_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Hub_SetUp_BrowseButtonString {
            get {
                return ResourceManager.GetString("Hub_SetUp_BrowseButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use ProFile HUB you will need to link to your clients’ files. During setup ProFile HUB will ready your files, so you may invite and collaborate with your clients..
        /// </summary>
        public static string Hub_SetUp_Description {
            get {
                return ResourceManager.GetString("Hub_SetUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are your client files stored?.
        /// </summary>
        public static string Hub_SetUp_FileStorage {
            get {
                return ResourceManager.GetString("Hub_SetUp_FileStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are your ProFile client files stored?.
        /// </summary>
        public static string Hub_SetUp_FileStorageType {
            get {
                return ResourceManager.GetString("Hub_SetUp_FileStorageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file path is invalid.
        /// </summary>
        public static string Hub_SetUp_InvalidFolderString {
            get {
                return ResourceManager.GetString("Hub_SetUp_InvalidFolderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following path is not supported as it is not a local disk.
        /// </summary>
        public static string Hub_SetUp_InvalidFolderStringNotLocal {
            get {
                return ResourceManager.GetString("Hub_SetUp_InvalidFolderStringNotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following path is not supported as it is not a network disk.
        /// </summary>
        public static string Hub_SetUp_InvalidNetworkFolderString {
            get {
                return ResourceManager.GetString("Hub_SetUp_InvalidNetworkFolderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Server - only you can access.
        /// </summary>
        public static string Hub_SetUp_LocalServerString {
            get {
                return ResourceManager.GetString("Hub_SetUp_LocalServerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this option will scan your entire computer for ProFile files..
        /// </summary>
        public static string Hub_SetUp_MultipleFolderInfoString {
            get {
                return ResourceManager.GetString("Hub_SetUp_MultipleFolderInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My files are in multiple folders..
        /// </summary>
        public static string Hub_SetUp_MultipleFolderString {
            get {
                return ResourceManager.GetString("Hub_SetUp_MultipleFolderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Server is currently unavailable! Please choose a local folder..
        /// </summary>
        public static string Hub_SetUp_NetworkProhibitedString {
            get {
                return ResourceManager.GetString("Hub_SetUp_NetworkProhibitedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one user may work on a file at a time. Additional users will get a &apos;file locked&apos; message until the first user closes/saves the file..
        /// </summary>
        public static string Hub_SetUp_NetworkServerSelectedString {
            get {
                return ResourceManager.GetString("Hub_SetUp_NetworkServerSelectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Server – shared server on the network.
        /// </summary>
        public static string Hub_SetUp_NetworkServerString {
            get {
                return ResourceManager.GetString("Hub_SetUp_NetworkServerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, Hub and Link only work with Tax Year 2015 and 2016 T1/TP1 files..
        /// </summary>
        public static string Hub_SetUp_Note {
            get {
                return ResourceManager.GetString("Hub_SetUp_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: .
        /// </summary>
        public static string Hub_SetUp_NoteText {
            get {
                return ResourceManager.GetString("Hub_SetUp_NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we index the files for you.
        /// </summary>
        public static string HUB_Setup_Progress_Message {
            get {
                return ResourceManager.GetString("HUB_Setup_Progress_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read files.
        /// </summary>
        public static string Hub_SetUp_ReadFileButtonString {
            get {
                return ResourceManager.GetString("Hub_SetUp_ReadFileButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to setup.
        /// </summary>
        public static string Hub_Setup_SetupButton_Key {
            get {
                return ResourceManager.GetString("Hub_Setup_SetupButton_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Hub Set Up.
        /// </summary>
        public static string Hub_SetUp_Title {
            get {
                return ResourceManager.GetString("Hub_SetUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will clear the existing data within Hub. Are you sure you want to proceed?.
        /// </summary>
        public static string HUB_Setup_Warning_Message {
            get {
                return ResourceManager.GetString("HUB_Setup_Warning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Hub is the digital assistant which helps you manage your clients’ documents..
        /// </summary>
        public static string Hub_Setup_WelcomeMessage_Key {
            get {
                return ResourceManager.GetString("Hub_Setup_WelcomeMessage_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ProFile Hub.
        /// </summary>
        public static string Hub_Setup_WelcomeMessageHeader_Key {
            get {
                return ResourceManager.GetString("Hub_Setup_WelcomeMessageHeader_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENT INFORMATION.
        /// </summary>
        public static string Hub_T1_Client_Info_Header {
            get {
                return ResourceManager.GetString("Hub_T1_Client_Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA Import.
        /// </summary>
        public static string Hub_T1_CRAImport_Header {
            get {
                return ResourceManager.GetString("Hub_T1_CRAImport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA COLLECTION.
        /// </summary>
        public static string Hub_T1_Data_Collection_Header {
            get {
                return ResourceManager.GetString("Hub_T1_Data_Collection_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE NAME.
        /// </summary>
        public static string Hub_T1_File_Name_Header {
            get {
                return ResourceManager.GetString("Hub_T1_File_Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTUIT LINK.
        /// </summary>
        public static string Hub_T1_Intuit_Link_Header {
            get {
                return ResourceManager.GetString("Hub_T1_Intuit_Link_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENTS.
        /// </summary>
        public static string Hub_T1_Last_Note_Header {
            get {
                return ResourceManager.GetString("Hub_T1_Last_Note_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST SAVED.
        /// </summary>
        public static string HUB_T1_Last_Saved_Header {
            get {
                return ResourceManager.GetString("HUB_T1_Last_Saved_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string Hub_T1_Name_Header {
            get {
                return ResourceManager.GetString("Hub_T1_Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES AND STATUS.
        /// </summary>
        public static string Hub_T1_Notes_And_Status_Header {
            get {
                return ResourceManager.GetString("Hub_T1_Notes_And_Status_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string Hub_T1_Status_Header {
            get {
                return ResourceManager.GetString("Hub_T1_Status_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we open the file for you....
        /// </summary>
        public static string Hub_T1Action_FileOpenString {
            get {
                return ResourceManager.GetString("Hub_T1Action_FileOpenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string Hub_T1Action_OpenFileString {
            get {
                return ResourceManager.GetString("Hub_T1Action_OpenFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select files for other actions!.
        /// </summary>
        public static string Hub_T1Action_SelectFileInfoString {
            get {
                return ResourceManager.GetString("Hub_T1Action_SelectFileInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Files.
        /// </summary>
        public static string Hub_T1Action_SelectFileString {
            get {
                return ResourceManager.GetString("Hub_T1Action_SelectFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action(s).
        /// </summary>
        public static string Hub_T1ActionBar_ActionsString {
            get {
                return ResourceManager.GetString("Hub_T1ActionBar_ActionsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Hub_T1ActionBar_TooltipString {
            get {
                return ResourceManager.GetString("Hub_T1ActionBar_TooltipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Hub_UnavailableString {
            get {
                return ResourceManager.GetString("Hub_UnavailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we update the link status for you.
        /// </summary>
        public static string HUB_UpdateLinkStatusProgressMessage {
            get {
                return ResourceManager.GetString("HUB_UpdateLinkStatusProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Message.
        /// </summary>
        public static string ImportantMessageString {
            get {
                return ResourceManager.GetString("ImportantMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Notification.
        /// </summary>
        public static string Notifications_MessageBox_Title {
            get {
                return ResourceManager.GetString("Notifications_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have mutiple notifications. Please open the ProFile Notification Centre to view these notifications.
        /// </summary>
        public static string Notifications_MultipleMessages_Message_Key {
            get {
                return ResourceManager.GetString("Notifications_MultipleMessages_Message_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Notification(s).
        /// </summary>
        public static string Notifications_MultipleMessages_Title_Key {
            get {
                return ResourceManager.GetString("Notifications_MultipleMessages_Title_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Notification Centre.
        /// </summary>
        public static string Notifications_ProFileMessageCenter_Key {
            get {
                return ResourceManager.GetString("Notifications_ProFileMessageCenter_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for more ....
        /// </summary>
        public static string Notifications_ProfileMessageCenter_Tooltip_Key {
            get {
                return ResourceManager.GetString("Notifications_ProfileMessageCenter_Tooltip_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Notifications_Settings_ClearAll {
            get {
                return ResourceManager.GetString("Notifications_Settings_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Disturb.
        /// </summary>
        public static string Notifications_Settings_DND {
            get {
                return ResourceManager.GetString("Notifications_Settings_DND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Notification Centre.
        /// </summary>
        public static string Notifications_Settings_OpenCenter {
            get {
                return ResourceManager.GetString("Notifications_Settings_OpenCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Notifications_Settings_Settings {
            get {
                return ResourceManager.GetString("Notifications_Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile Notification Centre.
        /// </summary>
        public static string NotificationSettings_ToolTip {
            get {
                return ResourceManager.GetString("NotificationSettings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to activate..
        /// </summary>
        public static string OnePay_ActivateLicense {
            get {
                return ResourceManager.GetString("OnePay_ActivateLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with a representative..
        /// </summary>
        public static string OnePay_aRep {
            get {
                return ResourceManager.GetString("OnePay_aRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business number.
        /// </summary>
        public static string OnePay_BusinessNumberTitle {
            get {
                return ResourceManager.GetString("OnePay_BusinessNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to carry forward..
        /// </summary>
        public static string OnePay_carryForward {
            get {
                return ResourceManager.GetString("OnePay_carryForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here .
        /// </summary>
        public static string OnePay_ClickHereLink {
            get {
                return ResourceManager.GetString("OnePay_ClickHereLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal name of corporation.
        /// </summary>
        public static string OnePay_CorpNameTitle {
            get {
                return ResourceManager.GetString("OnePay_CorpNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have a license?.
        /// </summary>
        public static string OnePay_ExistingLicense {
            get {
                return ResourceManager.GetString("OnePay_ExistingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string OnePay_FName {
            get {
                return ResourceManager.GetString("OnePay_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Trial License.
        /// </summary>
        public static string OnePay_GetTrialLicense {
            get {
                return ResourceManager.GetString("OnePay_GetTrialLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important! .
        /// </summary>
        public static string OnePay_Important {
            get {
                return ResourceManager.GetString("OnePay_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before clicking Next, make sure the above information is correct. You will not be able to change this information later. .
        /// </summary>
        public static string OnePay_ImportantText {
            get {
                return ResourceManager.GetString("OnePay_ImportantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFile automatically stores your OnePay authorization in the tax return file. You must save the file as soon as you click &quot;Finish&quot; to protect your purchase. .
        /// </summary>
        public static string OnePay_ImportantTransactionCompleted {
            get {
                return ResourceManager.GetString("OnePay_ImportantTransactionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or learn more by starting a .
        /// </summary>
        public static string OnePay_LearnMore {
            get {
                return ResourceManager.GetString("OnePay_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to purchase a ProFile OnePay license for the {0} T1/TP1. This license will allow you to prepare a single T1/TP1 tax return for the client specified below. .
        /// </summary>
        public static string OnePay_LicensePurchaseText {
            get {
                return ResourceManager.GetString("OnePay_LicensePurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnePay License Purchase.
        /// </summary>
        public static string OnePay_LicensePurchaseTitle {
            get {
                return ResourceManager.GetString("OnePay_LicensePurchaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live chat.
        /// </summary>
        public static string OnePay_LiveChatLink {
            get {
                return ResourceManager.GetString("OnePay_LiveChatLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string OnePay_LName {
            get {
                return ResourceManager.GetString("OnePay_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing 15 or more returns? .
        /// </summary>
        public static string OnePay_MoreThan15Returns {
            get {
                return ResourceManager.GetString("OnePay_MoreThan15Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing 4 or more returns? .
        /// </summary>
        public static string OnePay_MoreThan4Returns {
            get {
                return ResourceManager.GetString("OnePay_MoreThan4Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To obtain a free trial license code visit .
        /// </summary>
        public static string OnePay_ObtainLicense {
            get {
                return ResourceManager.GetString("OnePay_ObtainLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or call 1-800-452-9970.
        /// </summary>
        public static string OnePay_Phone {
            get {
                return ResourceManager.GetString("OnePay_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Next&quot; to purchase a OnePay license. This will provide you with the ability to prepare and file a single ProFile T2 return..
        /// </summary>
        public static string OnePay_Proceedt2Text {
            get {
                return ResourceManager.GetString("OnePay_Proceedt2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Next&quot; to purchase a OnePay license. This will provide you with the ability to prepare and file a single ProFile T3/TP-646 return..
        /// </summary>
        public static string OnePay_Proceedt3Text {
            get {
                return ResourceManager.GetString("OnePay_Proceedt3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Next&quot; to purchase a OnePay license. This will provide you with the ability to prepare and file a single ProFile T1/TP1 return..
        /// </summary>
        public static string OnePay_ProceedText {
            get {
                return ResourceManager.GetString("OnePay_ProceedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you are carrying forward from a previous version of Profile, you must do so before continuing with OnePay. .
        /// </summary>
        public static string OnePay_ProceedTextCommon {
            get {
                return ResourceManager.GetString("OnePay_ProceedTextCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we redirect you to our Purchase wizard..
        /// </summary>
        public static string OnePay_ProcessingText {
            get {
                return ResourceManager.GetString("OnePay_ProcessingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Request .....
        /// </summary>
        public static string OnePay_ProcessingTitle {
            get {
                return ResourceManager.GetString("OnePay_ProcessingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.intuit.ca.
        /// </summary>
        public static string OnePay_ProfileLink {
            get {
                return ResourceManager.GetString("OnePay_ProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase a ProFile OnePay.
        /// </summary>
        public static string OnePay_PurchaseProfileTitle {
            get {
                return ResourceManager.GetString("OnePay_PurchaseProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase our Unlimited License.
        /// </summary>
        public static string OnePay_PurchaseUnlimitedLicenseLink {
            get {
                return ResourceManager.GetString("OnePay_PurchaseUnlimitedLicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN.
        /// </summary>
        public static string OnePay_Sin {
            get {
                return ResourceManager.GetString("OnePay_Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to purchase a ProFile OnePay license for the {0} T2. This license will allow you to prepare a single T2 tax return for the client specified below..
        /// </summary>
        public static string OnePay_T2LicensePurchaseText {
            get {
                return ResourceManager.GetString("OnePay_T2LicensePurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to purchase a ProFIle OnePay license for the {0} T3.  This license will allow you to prepare a single T3/TP-646 tax return for the client specified below..
        /// </summary>
        public static string OnePay_T3LicensePurchaseText {
            get {
                return ResourceManager.GetString("OnePay_T3LicensePurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taxation year end.
        /// </summary>
        public static string OnePay_TaxationEndYear {
            get {
                return ResourceManager.GetString("OnePay_TaxationEndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxation year start.
        /// </summary>
        public static string OnePay_TaxationStartYear {
            get {
                return ResourceManager.GetString("OnePay_TaxationStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your online purchase transaction is completed. A purchase receipt will be sent to your email address..
        /// </summary>
        public static string OnePay_TransactionCompletedText {
            get {
                return ResourceManager.GetString("OnePay_TransactionCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Completed.
        /// </summary>
        public static string OnePay_TransactionCompletedTitle {
            get {
                return ResourceManager.GetString("OnePay_TransactionCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to complete your transaction. Please try again later..
        /// </summary>
        public static string OnePay_TransactionIncompletedText {
            get {
                return ResourceManager.GetString("OnePay_TransactionIncompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Incomplete.
        /// </summary>
        public static string OnePay_TransactionIncompletedTitle {
            get {
                return ResourceManager.GetString("OnePay_TransactionIncompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the trust.
        /// </summary>
        public static string OnePay_TrustNameTitle {
            get {
                return ResourceManager.GetString("OnePay_TrustNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Number.
        /// </summary>
        public static string OnePay_TrustNumber {
            get {
                return ResourceManager.GetString("OnePay_TrustNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string OnePayAttentionTitleKey {
            get {
                return ResourceManager.GetString("OnePayAttentionTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string OnePayBackStringKey {
            get {
                return ResourceManager.GetString("OnePayBackStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we load the payment screen.
        /// </summary>
        public static string OnePayBrowserLoadMessageKey {
            get {
                return ResourceManager.GetString("OnePayBrowserLoadMessageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OnePayCancelStringKey {
            get {
                return ResourceManager.GetString("OnePayCancelStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string OnePayFinishStringKey {
            get {
                return ResourceManager.GetString("OnePayFinishStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string OnePayNextStringKey {
            get {
                return ResourceManager.GetString("OnePayNextStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your purchase is complete. You must.
        /// </summary>
        public static string OnePayPaymentMessagePartOne {
            get {
                return ResourceManager.GetString("OnePayPaymentMessagePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to apply your One Pay License.
        /// </summary>
        public static string OnePayPaymentMessagePartThree {
            get {
                return ResourceManager.GetString("OnePayPaymentMessagePartThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  close this window.
        /// </summary>
        public static string OnePayPaymentMessagePartTwo {
            get {
                return ResourceManager.GetString("OnePayPaymentMessagePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Screen.
        /// </summary>
        public static string OnePayPaymentScreenTitle {
            get {
                return ResourceManager.GetString("OnePayPaymentScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string OnePayRetryStringKey {
            get {
                return ResourceManager.GetString("OnePayRetryStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the following error(s):.
        /// </summary>
        public static string OnePayValidationErrorInstructionKey {
            get {
                return ResourceManager.GetString("OnePayValidationErrorInstructionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Missing/Invalid Business number.
        /// </summary>
        public static string OnePayValidationErrorInvalidBN {
            get {
                return ResourceManager.GetString("OnePayValidationErrorInvalidBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Missing/Invalid Date.
        /// </summary>
        public static string OnePayValidationErrorInvalidDate {
            get {
                return ResourceManager.GetString("OnePayValidationErrorInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Missing/Invalid Name.
        /// </summary>
        public static string OnePayValidationErrorInvalidName {
            get {
                return ResourceManager.GetString("OnePayValidationErrorInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Missing/Invalid SIN number.
        /// </summary>
        public static string OnePayValidationErrorInvalidSin {
            get {
                return ResourceManager.GetString("OnePayValidationErrorInvalidSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s).
        /// </summary>
        public static string OnePayValidationErrorTitleKey {
            get {
                return ResourceManager.GetString("OnePayValidationErrorTitleKey", resourceCulture);
            }
        }
    }
}
